#!/usr/bin/with-contenv bash

#Set helper vars
CODENAME="$(cat /etc/os-release | grep 'UBUNTU_CODENAME' | cut -d '=' -f 2)"
VERSION="$(cat /etc/os-release | grep 'VERSION=' | cut -d '=' -f 2)"
BUILDDATE=`date`

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "
-------------------------------------
### Powered by Ubuntu Core ###

OS: Ubuntu ${VERSION}
Based on: https://partner-images.canonical.com/core/${CODENAME}/current/ubuntu-${CODENAME}-core-cloudimg-amd64-ro$
Build @: ${BUILDDATE}

Rebuild/Updated every week.

# Thies88 #
-------------------------------------"
echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
# Set permissions.
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults

#drop helper variables used in this script.
unset CODENAME
unset VERSION
unset BUILDDATE
unset PUID
unset PGID
